version: 2
jobs:
  build:

    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
